add_includedirs("$(projectdir)/tests")
add_includedirs("$(projectdir)/include/msl")

includes("test_difference")
includes("test_equation")
includes("test_integral")
includes("test_interp")
includes("test_matrix")
includes("test_ode")
includes("test_polynomial")
includes("test_signal")
